# Cloudflare Workers 配置文件
name = "psychat-anthropic-proxy"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "production"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "psychat-logs"
database_id = "418b4f32-d109-4b90-ac89-46a4ad7ac3f3"

# KV 存储绑定（用于速率限制）
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "c4ea20fbd46b460eac5a53f4dfd1b63b"

## Queue 绑定（可选，用于异步处理）
#[[queues.producers]]
#binding = "LOG_QUEUE"
#queue = "psychat-log-queue"
#
#[[queues.consumers]]
#queue = "psychat-log-queue"
#max_batch_size = 10
#max_batch_timeout = 30

# Cron 触发器（每天凌晨2点清理数据）
[triggers]
crons = ["0 2 * * *"]

# 环境特定配置
[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
